export enum States {
    TUNIS= 'Tunis',
    ARIANA= 'Ariana',
    MANOUBA= 'Manouba',
    BENAROUS= 'Ben Arous',
    NABEUL= 'Nabeul',
    ZAGHOUAN= 'Zaghouan',
    BEJA= 'Béja',
    JENDOUBA= 'Jendouba',
    KASSERINE= 'Kasserine',
    KEF= 'Kef',
    SILIANA= 'Siliana',
    SOUSSE= 'Sousse',
    MONASTIR= 'Monastir',
    MAHDIA= 'Mahdia',
    SFAX= 'Sfax',
    KAIROUAN= 'Kairouan',
    SIDI_BOUZID= 'Sidi Bouzid',
    GAFSA= 'Gafsa',
    TOZEUR= 'Tozeur',
    KEBILI= 'Kébili',
    MEDENINE= 'Medenine',
    TATAOUINE= 'Tataouine',
    GABES= 'Gabès'
}